import Footer from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import type { Metadata, Viewport } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div className="fixed inset-0 w-full">
        <Image src={"/images/bg.jpg"} fill alt="background" />
      </div>
      <Navbar />
      <main>
        {children}
      </main>
      <Footer />
    </div>
  );
}
