import { HeroLanding } from "@/components/landing/hero";
import Footer from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import type { Metadata, Viewport } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <Navbar />
      <main>
        <HeroLanding />
        <div className="bg-white h-[40vh] inset-0" />
        {children}
      </main>
      <Footer />
    </div>
  );
}
